sonar.projectKey=zmathmatos_fiap-x
sonar.organization=zmathmatos

sonar.sources=packages/shared/src,apps/video-api/src,apps/video-processor/src,apps/notification-service/src,apps/web/src
sonar.tests=packages/shared/tests,apps/video-api/tests,apps/video-processor/tests,apps/notification-service/tests,apps/web/tests

sonar.javascript.lcov.reportPaths=packages/shared/coverage/lcov.info,apps/video-api/coverage/lcov.info,apps/video-processor/coverage/lcov.info,apps/notification-service/coverage/lcov.info,apps/web/coverage/lcov.info

sonar.exclusions=**/dist/**,**/node_modules/**,**/coverage/**,**/*.config.js,**/*.config.ts
sonar.coverage.exclusions=**/tests/**,**/features/**,**/*.d.ts,**/main.tsx,**/server.ts,**/worker.ts,**/container.ts,**/migrations/**

sonar.sourceEncoding=UTF-8
